disabled_rules:
- multiple_closures_with_trailing_closure
- unused_closure_parameter
- trailing_newline
- trailing_whitespace
- todo

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 105
    error: 150
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 1
    error: 300
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 100
    error: 300
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 10
    error: 25
    
force_cast: warning
force_try:
    severity: warning
    
reporter: "xcode"
