name: CI

# Controls when the workflow will run
on:
  push:

  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest

    steps:
        
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.3
