name: SwiftLint

on:

  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter html > swiftlint.html
        # run: swiftlint lint --reporter github-actions-logging
